# Generated by Django 3.2.4 on 2023-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
    ]
