# Generated by Django 3.2.4 on 2023-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_gen', '0002_saved_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_images',
            name='ai_image_url',
        ),
        migrations.AddField(
            model_name='saved_images',
            name='ai_img',
            field=models.ImageField(default='null', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
